
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development: &development
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 192.168.99.100
  port: 32768
  username: postgres
  database: development

test: &test
  <<: *development
  database: testing

integration:
 <<: *test
 database: integration

production:
  <<: *default
  database: db/production.sqlite3
