
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development: &development
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: dsc_development

test: &test
  <<: *development
  database: testing

integration:
 <<: *test
 database: integration

production:
  <<: *default
  database: db/production.sqlite3
