language: node_js
node_js:
  - "4.1"

cache:
  directories:
    - node_modules
    - bower_components

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - npm install -g bower
  - npm install -g gulp
  - bower install

script:
 - gulp test
 - gulp protractor
