env:
  global:
  - CF_APP=techireland-be
  - CF_API=run.pivotal.io
  - CF_ORGANIZATION=TechIreland
  - CF_SPACE=development
  - secure: cOhMbcacXxGvbsQlr/YKVVvkAmLJ7WL/iWhbDTLvWE7JTuj4cdFO3/hfLKnIrdX0bFKhkYsDZ69qL+MA7Y5buodijxg9AZdhsaJy6WPg7ZhzkaAs4+WajhuK8dEk7ILLX5Z1e5i+yF/tGkbd6K/E1BQl26dTmAKV36cA5/tIgSklB6ZyTEUaHco6fg7s7szRP/4p1iwGjdvnMmHJUIScZrLGJPsPJWo9bmn8OKGbwkzPadT/Rt5PFVl+8IT11a6GOuKKR42h+EnksZ99zcPNbLtx06aCNgQd+Z63jdmPBYflzVPnCpGx/ZoaC53OAA8qZPLbpFkV6kqgU6/sUHi7/evK5JKqtBxucoXYVIWV5xbDOPqd46DwrxE+qVdMVWNuqInooy2qdpPjlLkf71DOPKbqD2ptgPPvOgRw2M1yuNpRq38LWBDHsTkxMhygfgv/IJgZ5QNFToGuXeN3e3alVNojoQB+brXSuh1iGT2YVQpUKzP8qb0+5Ko5qWDLTQtqGV8ZwukNh7fxssS/ppRcdE3DzV/BZ/tlfhCYTDIG18lc01PmOt2p5Wsse9tDKK9zBh9GOSml74SJu3AVncxtKM2UPl8wBptdlDq8kJWtiu27AhQVJHX0rcDRUDR0HT51QhRJBiwqsKN6xe5rfee7e3DBMKnNte81hkQbtETF69I=
  - secure: Wzi4rVVg/9Z6C9+o6ziKWVqprVgIymruY/mlJiOXuXOKQAvfg1DatUPA2EkfAp2kZlgMN0d5EzXUaqmIRBGX7C2n5+PZOPb2f+koHHwpUW9iOUgDraGiVjg2yxoRPfdw8L4kscFMa6WQm+++PONMJmvt1aoeAtMouwEB/dehdVVNCDn+9O5dOVnPOEYdeEMqpZbgf9CrfyOyGQylMMc1WsVR0gC8fChHYXfe1wUHlDy/Dls72jX5jJXf7Monin3EfXwuqG+X/h4eNpIrpiZ4ED7OagvukAUIYzfV4aQ44V6ZE8eZ4z7cRVeeOUrdcq/vauBixCc2yw7bdgpHMCg6zt96BV42ILQ1j6d8lBHmRUB6gQKM+anMGmOMFYYo4cs/RvJUC2dF+gPQARVpWfO9xGQCHBCx6jgui+tYWt0wGwD7TaAZORtlVrgFSWU1vNtn3hQVSMdNjqUdKHo0Ax7gePrleOLBOkf/l7hLtcPsC6HvDu92MxxEjEUcEtBHHLeH60NUwQSPnpOhRjmnhMaChwQXVhgfhMipopKu4jcrCSlFSub7p9W9wfvjgOrKap4+FGZ6ZhlJvCMyeegPUR5vD3SJ4lGrNrPjYkxLtaAuxLcSTwHkPsxd6cdOjsHzggiRKky43z+THBUgKIWnFZkBO/Z2oglGR8RM8xiyNiQLdhc=
  - secure: kl17PjObCfB84mQXudkDIS3+tmJ0vxSN8oc0f9g6vXTP0Dn31qenT9OQ/zOwlqQ+NMM6M5PXkCy4JER6LRifgR1+PYcBKwIaYm3eWDKsfJI8eWSdpNpgNWSdnswsxBat8OiPIM/I1ypFX7dNs++pn5vCo2RCUErz5k5X7qNGag7Sw4U6oS/OpNkGsVUKoLjquw4Za+ZVDonfKQq9YpaLRXSLeDjNFHDuh2GqueVz7el6COMBLMZcHfvMUs24AhhgQWKh918znlRIieDKAvsS7SxzkmBXw7zeiMFGcH86ZtblfexmgdtSW8OHzToyL6beTR3jQGUbV5o2h0PvTH1Bo43zD1YQBTmBbXpIFlxGr/dLtvZjT/JMBoU28AZzTivAwrqllMrMlf9qaYCUW8ihfYI818KuApBqf0VIS4sHI7DyuWElgtEhvEXP+Ny5d4ynWtwpBORPLuV1fTjrqOL67VueeJzcHIjM8TfjZrBINGq2uex9JC1TfMxmnXbuYCxzhRRbkf3WPdQLIjDX/FXCpT9kDufgszZ+53oEuhE8p/GgljEoqhMdKrh/hu+Aq+ieUMEIqhnvQvS2ak6rJOmCNjdiEDDM52oFYi/8iZG+gs5QATkGOsMCYTbnPPcjp3ClbGUQL3gq4dnPtMBxEODF9g7Ars4noJeth5rx83ZTbxA=

addons:
  postgresql: " 9.4"

services:
  - postgresql

language: ruby

rvm:
  - 2.2.3

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - node_modules

install:
  - ". $HOME/.nvm/nvm.sh"
  - nvm install stable
  - nvm use stable
  - npm install
  - gem install sass
  - npm install -g bower
  - npm install -g gulp
  - bower install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - echo 'START BACKEND TESTS'
  - cd server/dsc-db-be && bundle install
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test rake db:create
  - rspec
  - echo 'END BACKEND TESTS'
  - RAILS_ENV=integration rake db:create
  - RAILS_ENV=integration rake db:drop db:create db:migrate db:seed
  - RAILS_ENV=integration rails s -p 4000 > /dev/null &
  - cd ../../
  - echo 'START FRONTEND UNIT TESTS'
  - gulp test
  - echo 'END FRONTEND UNIT TESTS'

before_deploy:
  - cp src/app/ngConstants.js.prod src/app/ngConstants.js
  - gulp build

deploy:
  provider: cloudfoundry
  edge: true
  username: cathal@startupdublin.com
  password:
    secure: eAyU5fggKo9v2RFvm5zEghRtSSZUfy+j/aet4V+OjR3iwv3qM9e8hz4hP/DXFECt4zs1DzkMXKPoM0h6LQmh7IMdHjxYzMNejVLUDoBHD1h61th9g7Qym/SXO/vUF5lye2Z9V+iZUR2PvL3+I5WLSZJe8/p8CJhbQCkLHyGuU4A6sKC0tERTHmtFs1j9ZdmerBszXlX2mQ9GhCx3fubz8KTwoc+5Comovr6cuTpcgdMpLRgxrv7vpKzaJJCPS9bGAVbKGn8bfJhQxM/jB4ULffXuKaDM80NkGsfVZdR8ZGLCGV2SPc7ZA+3vD/WEzMbJETDFF6SiIZSxWlUoTCW0ctWDFgvROzSxmVwVL0I2wMWH49afvM3CXGuP64EvHPpdU2Xmfk7qYODici2FM3O2mkCzCHcONhCIeqMhyawSBKNobl5GshI5Hq++BxBHwblpddpn9J34hquWfiZoOcV3G/GOMH3Ncj1aoYeN5Wvr1teARB5jyPMD77rZirkNE2+cpa8VDe9L0Ltj6c1fSOOXc4HXYE2G2B6/RxZ7wfmHH6U+cS6WSh7t20/fDHo7qSM50c9yUPFrg7E0KECg8ak1wdhf+/kXeAB37m0/6qEwmf9rnwnt73yeWXCgTyvL46klPfcmRcRd1iU/eNLdRU+tJmm9r8gAYdXJzqJN3RYbMbE=
  api: https://api.run.pivotal.io
  organization: TechIreland
  space: development
