addons:
  postgresql: "9.3"

services:
  - postgresql

language: ruby

rvm:
  - 2.2.3

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - gem install sass
  - npm install -g bower
  - npm install -g gulp
  - bower install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp test
  - cd server/dsc-db-be && bundle install
  - cp config/database.yml.travis config/database.yml
  - rake db:schema:load db:seed
  - rails s -p 4000 > /dev/null &
  - cd ../../
  - sleep 10
  - gulp protractor

before_deploy:
  - cp src/app/ngConstants.js.prod src/app/ngConstants.js
  - gulp build


deploy:
  provider: cloudfoundry
  edge: true
  username: bgadelhahammarlund@pivotal.io
  password:
    secure: u0SEOPeSk6fd23oz3uYXnlJe+eOIqWNbBIbqSmMqML614m6hVS7Ko18QBfHeFfy/MFvMVjL7RB6+yMIEhnoCebTtYmmfrLCzCW/9CnsHdkC600oOzIE3IAPFQhi0RsLy9ktrMvBqhg4unUWPL6O17hqSWqVQvMBr8TJKYhvb/2cMiPSallGnVwZiV/eEOG5mhNVuhzq2LecFgwNikhN7wTZnXNmUGwmeonxpl+zYW/xlZa42BzDlQb6R7kf6JBgDxgIn5msU1ED82sorh6pccsubJZq/WTpJt6AtH3NtlGpBEMSI0viu1SaZPgqDS4yf8e4DODOiOKVCwGJquXLzq/1pr2rbj96up8gFuI8ZjMMogQrNwZsG8Ddk51h3lvTXZGuR8g7gR3nRiXw/mmyUHhmpGqxdtLqAGLNJdxmXSoPNgwaYqQV04XsdCiPzi6ykAS+fdOsKFb8p6REsl0cUhp2t6KyNE171UmVHORViK5z7mfwwutue00lvh4sBzTiXDCPVOcACGvVNdVFfoafgx3SuF+1zs1Yw73r35pj0fWPl1vISHOTpoFfWHh3OLdpNXRGLY4BhGDhkCio8BxVeVsowRPa3puo0aNmZPWHANYwD5C3pzTRipbp1w7IeC2aQy9nG3SfSG9XFC8MsSBkjKkZl+IlybijnQzWcEJ0PtiM=
  api: https://api.run.pivotal.io
  organization: bengt-org
  space: development
