language: node_js

node_js:
  - '4.1'

cache:
  directories:
    - node_modules
    - bower_components

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install sass
  - npm install -g bower
  - npm install -g gulp
  - bower install

script:
  - gulp test
  - gulp protractor

before_deploy:
  - gulp build

deploy:
  edge: true
  provider: cloudfoundry
  username: bgadelhahammarlund@pivotal.io
  password:
    secure: u0SEOPeSk6fd23oz3uYXnlJe+eOIqWNbBIbqSmMqML614m6hVS7Ko18QBfHeFfy/MFvMVjL7RB6+yMIEhnoCebTtYmmfrLCzCW/9CnsHdkC600oOzIE3IAPFQhi0RsLy9ktrMvBqhg4unUWPL6O17hqSWqVQvMBr8TJKYhvb/2cMiPSallGnVwZiV/eEOG5mhNVuhzq2LecFgwNikhN7wTZnXNmUGwmeonxpl+zYW/xlZa42BzDlQb6R7kf6JBgDxgIn5msU1ED82sorh6pccsubJZq/WTpJt6AtH3NtlGpBEMSI0viu1SaZPgqDS4yf8e4DODOiOKVCwGJquXLzq/1pr2rbj96up8gFuI8ZjMMogQrNwZsG8Ddk51h3lvTXZGuR8g7gR3nRiXw/mmyUHhmpGqxdtLqAGLNJdxmXSoPNgwaYqQV04XsdCiPzi6ykAS+fdOsKFb8p6REsl0cUhp2t6KyNE171UmVHORViK5z7mfwwutue00lvh4sBzTiXDCPVOcACGvVNdVFfoafgx3SuF+1zs1Yw73r35pj0fWPl1vISHOTpoFfWHh3OLdpNXRGLY4BhGDhkCio8BxVeVsowRPa3puo0aNmZPWHANYwD5C3pzTRipbp1w7IeC2aQy9nG3SfSG9XFC8MsSBkjKkZl+IlybijnQzWcEJ0PtiM=
  api: https://api.run.pivotal.io
  organization: bengt-org
  space: development

